name: Invitation to the OpInCo Organization
description: Invite me to OpInCo 🚀
title: "Invite me to OpInCo 🚀"
labels: [Invite on label]
This will send you an invite to join the GitHub Org of OpInCo Community
