on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: OpInCo-Community
          label: Invite on label
          repo-token: ${{ secrets.TOKEN_GITHUB }}
          comment: '<b>Invitation sent for the GitHub Organisation.</b>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
